steps:
# Build the container image
# Push the container image to Container Registry
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
      - '-c'
      - |
        docker build -t gcr.io/$PROJECT_ID/appython:${BUILD_ID} .
        docker tag appython:${BUILD_ID} gcr.io/$PROJECT_ID/appython:${BUILD_ID}
        docker push gcr.io/$PROJECT_ID/appython:${BUILD_ID}

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'appython', '--image', 'gcr.io/$PROJECT_ID/appython:${BUILD_ID}', '--region', 'us-central1','--allow-unauthenticated', '--platform', 'managed','--port','8080']
images:
- gcr.io/$PROJECT_ID/appython:${BUILD_ID}